name: Publish to Maven Central

on:
  release:
    types: [published]

permissions:
  contents: read
  actions: read

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
          fetch-depth: 0
          
      - name: Extract version from tag
        id: version
        run: |
          TAG="${{ github.event.release.tag_name }}"
          VERSION=${TAG#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "Publishing release: $TAG (version: $VERSION)"
          
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        
      - name: Verify version in build.gradle.kts
        run: |
          EXPECTED_VERSION="${{ steps.version.outputs.version }}"
          ACTUAL_VERSION=$(grep 'version = ' build.gradle.kts | sed 's/.*version = "\(.*\)".*/\1/')
          echo "Expected version: $EXPECTED_VERSION"
          echo "Actual version in build.gradle.kts: $ACTUAL_VERSION"
          
          if [ "$ACTUAL_VERSION" != "$EXPECTED_VERSION" ]; then
            echo "❌ Version mismatch! Expected $EXPECTED_VERSION but found $ACTUAL_VERSION"
            echo "This might indicate that the release was created from the wrong commit."
            exit 1
          fi
          echo "✅ Version verified: $ACTUAL_VERSION"
          
      - name: Run tests
        run: |
          echo "Running tests before publishing..."
          ./gradlew test
          echo "✅ All tests passed"
            
      - name: Publish to Maven Central
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
        run: |
          echo "Publishing to Maven Central..."
          ./gradlew publishAllPublicationsToMavenCentralRepository
          echo "✅ Published to Maven Central successfully"
          
      - name: Publish Summary
        run: |
          TAG="${{ steps.version.outputs.tag }}"
          VERSION="${{ steps.version.outputs.version }}"
          
          echo "📦 Artifact uploaded to Maven Central Portal successfully!"
          echo ""
          echo "📋 What was completed:"
          echo "✅ Tests passed"
          echo "✅ Artifact uploaded to Maven Central Portal (deployment created)"
          echo ""
          echo "🚨 MANUAL ACTION REQUIRED:"
          echo "1. Go to https://central.sonatype.com/"
          echo "2. Log in with your Maven Central credentials"
          echo "3. Navigate to 'Publish' in the navigation menu"
          echo "4. Find your deployment (Status: \"VALIDATED\")"
          echo "5. Review the deployment contents"
          echo "6. Click 'Publish' button"
          echo ""
          echo "🔗 Links:"
          echo "- GitHub Release: https://github.com/${{ github.repository }}/releases/tag/$TAG"
          echo "- Maven Central Portal: https://central.sonatype.com/"
          echo "- After manual publish: https://search.maven.org/artifact/io.github.haradakunihiko/php-json-deserializer-kt/$VERSION/jar"
          echo ""
          echo "⚠️  The release is NOT complete until you manually publish in Maven Central Portal!"
